apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
        api: external        
    spec:
      containers:
      - name: frontend
        image: docker.io/manenim/udagram-frontend:v4a    
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m               

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    service: frontend